name: env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - conda-forge::ruff
  - nbqa
  - numpy
  - pandas
  - pyarrow
  - pygments
  - prompt_toolkit
  - scikit-learn
  - matplotlib
  - mpi4py
